version: "3.3"
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'checkAgro-dev'
      MYSQL_USER: 'usr-checkAgro'
      MYSQL_PASSWORD: 'pwd-checkAgro'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted

x-mongo-container:
  image: mongo
  container_name: mongo-container
  restart: on-failure
  environment:
    MONGO_INITDB_DATABASE: 'customer-dev-mongo'
    MONGO_INITDB_ROOT_USERNAME: 'usr-customer-mongo'
    MONGO_INITDB_ROOT_PASSWORD: 'pwd-customer-mongo'
  ports:
    - 27017:27017
  expose:
    - 27017
  volumes:
    - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro